鲜花订购与管理系统/Controllers/FlowerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FlowerHouse.Models;
using FlowerHouse.Models.Entity;
using Microsoft.AspNetCore.Identity;

namespace FlowerHouse.Controllers
{
    public class FlowerController : Controller
    {
        private readonly FlowerHouseContext _context;

        public FlowerController(FlowerHouseContext context)
        {
            _context = context;
        }

        //private async Task<List<Flower>> GetFlowerList()
        //{
        //    var flowerList = await _context.Flowers.Include(f => f.Stock).Where(f => f.FlowerBuy >= 0).ToListAsync();
        //    return flowerList;
        //}

        //点击查看全部时列出所有花
        public async Task<IActionResult> List()
        {
            return View(await _context.Flowers.Include(f => f.Stock).Where(f => f.FlowerBuy >= 0).ToListAsync());
        }

        //鲜花详情页
        public async Task<IActionResult> Detail(int? id, [FromServices]UserManager<HouseUser> userManager)
        {
            string userId;
            if (User.Identity.IsAuthenticated)
            {
                userId = userManager.GetUserId(User);
            }
            if (id == null)
            {
                return NotFound();
            }
            var flower = await _context.Flowers.AsNoTracking().Include(f => f.Stock).Include(f => f.FlowerTags).ThenInclude(ft => ft.Tag)
                .FirstOrDefaultAsync(m => m.FlowerId == id);
            if (flower == null)
            {
                return NotFound();
            }
            return View(flower);
        }

        //标签
        public async Task<IActionResult> Tag(int? Id)
        {
            //取出该标签的所有花
            var flowerlist = await _context.Flowers.AsNoTracking().Include(f => f.Stock).Include(f => f.FlowerTags).Where(f => f.FlowerTags.Any(ft => ft.TagId == Id)).Where(f => f.FlowerBuy>=0).ToListAsync();

            //面包屑
            ViewBag.breadcrumb = (await _context.Tags.AsNoTracking().FirstOrDefaultAsync(t => t.TagId == Id)).TagName;

            return View("List", flowerlist);
        }

        //搜索
        public async Task<IActionResult> Search(string inputframe)
        {
            //查询 花名，花材，花语 是否包含keyword
            var flowerList = await _context.Flowers.Include(f => f.Stock).Where(f => (f.FlowerName.Contains(inputframe) || f.FlowerMaterial.Contains(inputframe) || f.FlowerEmblem.Contains(inputframe)) && f.FlowerBuy >=0).ToListAsync();

            //var flowerList = (await GetFlowerList()).Where(f => f.FlowerName.Contains(inputframe) || f.FlowerMaterial.Contains(inputframe) || f.FlowerEmblem.Contains(inputframe)).ToList();
            //查询 标签 是否包含keyword
            var tagList = await _context.Tags.AsNoTracking().Where(t => t.TagName.Contains(inputframe)).Include(t => t.FlowerTags).ThenInclude(ft => ft.Flower).ThenInclude(f => f.Stock).ToListAsync();

            if (tagList != null)
            {
                foreach (var tag in tagList)
                {
                    foreach (var ft in tag.FlowerTags)
                    {
                        flowerList.Add(ft.Flower);
                    }
                }
            }
            flowerList = flowerList.Where(f => f.FlowerBuy >= 0).ToList();
            if (flowerList.Count == 0)
            {
                ViewBag.tip = "无搜索结果";
            }
            //面包屑
            ViewBag.breadcrumb = inputframe;

            return View("List", flowerList);
        }
    }
}

鲜花订购与管理系统/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace 鲜花订购与管理系统.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

鲜花订购与管理系统/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using FlowerHouse.Models.Entity;
@inject SignInManager<HouseUser> SignInManager
@inject UserManager<HouseUser> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>花之家</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    @*@await RenderSectionAsync("Style", false)*@
    <link href="~/layui/layui/css/layui.css" />
    <script src="~/layui/layui/layui.all.js"></script>
    <link href="~/layui/layui/css/layui.css" />
</head>

<body>
    <div class="main">
        <div class="top-nav">
            <div class="navbox">
                <ul class="nav-left">
                    <li> <i class="fa fa-fort-awesome" aria-hidden="true">@Html.ActionLink("首页", "Index", "Home")</i></li>
                    |
                    <li>欢迎来到花之家!</li>
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    var user = await UserManager.GetUserAsync(User);
                    <ul class="nav-right">
                        @if (User.HasClaim(c => c.Type == "ManageHouse"))
                        {
                            <li><a href="/Admin/Flower/List">管理后台</a></li>
                        }
                        <li class="superior">
                            <a href="#">@user.UserName</a>
                            <div class="UserInformation">
                                <ul>
                                    <li>昵称: @user.UserName</li>
                                    <li>
                                        余额: @user.Balance
                                        <button class="layui-btn" data-method="recharge">充值</button>
                                    </li>
                                </ul>
                            </div>
                        </li>

                        <li><a href="/Account/LogOut">退出登录</a></li>
                        <li><a href="/Order/List">我的订单</a></li>

                        <li><a href="/ShoppingCart/CartDetail"><i class="fa fa-shopping-cart" aria-hidden="true"></i>&nbsp;购物车</a></li>
                    </ul>
                }
                else
                {

                    <ul class="nav-right">
                        <li>@Html.ActionLink("登录", "Login", "Account")</li>
                        |
                        <li>@Html.ActionLink("注册", "Login", "Account")</li>
                    </ul>
                }
            </div>
        </div>
        <div class="top">
            <div class="logo">
                <img src="~/images/logo.png" width="68" height="68" />花之家
            </div>
            <div class="query">
                <form asp-action="Search" asp-controller="Flower" method="get">
                    <input type="text" name="inputframe" placeholder="请输入你要搜索的内容" />
                    <input type="submit" value="搜索" />
                </form>
            </div>
            <div class="information">
                <div class="phone"><a href="#"><i class="fa fa-headphones fa-2x" aria-hidden="true"></i>在线客服</a></div>
                &nbsp; |
                <div class="phone"><i class="fa fa-volume-control-phone fa-2x" aria-hidden="true"></i>110-120-1120</div>
            </div>
        </div>

        <div class="container body-content">
            @RenderBody()
            <footer>
                <div class="footer-nav">
                    <div class="nav">
                        <div class="nav-left">
                            <ul>
                                <li class="li-title">客户服务</li>
                                <li><a href="#">隐私条款</a></li>
                                <li><a href="#">公司简介</a></li>
                                <li><a href="#">安全条款</a></li>
                                <li><a href="#">联系方式</a></li>
                                <li><a href="#">服务声明</a></li>
                            </ul>
                            <ul>
                                <li class="li-title">购物指南</li>
                                <li><a href="#">绿植寓意</a></li>
                                <li><a href="#">鲜花支数寓意</a></li>
                                <li><a href="#">购物须知</a></li>
                                <li><a href="#">送花礼仪</a></li>
                                <li><a href="#">如何购买</a></li>
                            </ul>
                            <ul>
                                <li class="li-title">支付方式</li>
                                <li><a href="#">支付方式</a></li>
                                <li><a href="#">银行转账</a></li>
                                <li><a href="#">在线补款</a></li>
                            </ul>
                            <ul>
                                <li class="li-title">配送信息</li>
                                <li><a href="#">关于配送</a></li>
                                <li><a href="#">定时配送</a></li>
                                <li><a href="#">配送说明</a></li>
                                <li><a href="#">发票说明</a></li>
                                <li><a href="#">配送范围及费用</a></li>
                            </ul>
                            <ul>
                                <li class="li-title">售后服务</li>
                                <li><a href="#">投诉建议</a></li>
                                <li><a href="#">订单查询</a></li>
                                <li><a href="#">取消订单</a></li>
                            </ul>
                        </div>
                        <div class="nav-right">
                            <ul>
                                <li>本地订花热线</li>
                                <li>770-880-1314</li>
                                <li>服务时间：24小时全天为您服务</li>
                                <li>客服工作时间：9:00-21:00</li>
                                <li>花之家欢迎您的来电！</li>
                                <li>蜀ICP备15011281号</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
   
    @RenderSection("Scripts", required: false)
    <script>
        layui.use('element', function () { });

        layui.use('layer', function () {
            var $ = layui.jquery, layer = layui.layer;

            //触发事件
            var active = {
                recharge: function () {
                    layer.open({
                        type: 1
                        , title: '用户充值'
                        , content: $('#lai')
                        , area: ['240px', '200px']
                        , anim: 1
                        , resize: false
                    });
                }
            };
            $('.UserInformation .layui-btn').on('click', function () {
                var othis = $(this), method = othis.data('method');
                active[method] ? active[method].call(this, othis) : '';
            });
        });
    </script>
   @* <form asp-action="payment" asp-controller="Account" method="post">
        <div id="lai" style="display:none">
            <p>请输入要充值的金额:<input type="text" name="num" value="" /></p>
            <input type="submit" name="" class="layui-btn" value="确认充值" />
        </div>
    </form>*@
</body>
</html>